In [3]:
import requests
import pandas as pd

In [15]:
# 
# Write a function that takes the parameters for world bank data
def get_worldbank_data(country_code, indicator_id, indicator_name, date_range):
    """
        get_worldbank_data gets development indicator data for a given country

        Params:
            country_name
            indicator_id
            indicator_name
            date_range

        Returns:
            DataFrame of the indicator per year over a given year range
    """
    url = f"https://api.worldbank.org/v2/country/{country_code}/indicator/{indicator_id}"
    paramitas = {
        'date': date_range,
        'format': 'json'
    }
    # 
    # Send the GET request to the API.
    respons = requests.get(url, params = paramitas)
    # 
    # Process returned data.
    if respons.status_code == 200:
        indicator_data = respons.json()
        # 
        # Get the data from the second element of returned data
        indicator_data = indicator_data[1]
        # 
        # Convert the list of dictionaries to DataFrame
        indicator_data_df = pd.DataFrame(indicator_data)
        # 
        # Filter the columns to show for the DataFrame
        indicator_data_df = indicator_data_df[['date', 'value']]
        # 
        # Rename the columns
        indicator_data_df = indicator_data_df.rename(
            columns = {
                'date': 'year',
                'value': f"{indicator_name}"
            }
        )
        return indicator_data_df
    else:
        print("Eror getting indicator data", respons.status_code)

In [19]:
# 
# Get Kenyan Population data from world bank data
ke_pop = get_worldbank_data("KE", "SP.POP.TOTL", "pop", "2008:2022")
ke_pop

    year       pop
0   2022  54252461
1   2021  53219166
2   2020  52217334
3   2019  51202827
4   2018  50207107
5   2017  49197766
6   2016  48139687
7   2015  47088526
8   2014  46051440
9   2013  44986791
10  2012  43888303
11  2011  42758461
12  2010  41598567
13  2009  40408891
14  2008  39206351