# Lab 7
<br>

# Object-Oriented Programming (OOP I)
---

##### CS1P. Semester 2. Python 3.x
 ---

In [3]:
from utils.tick import tick

## Purpose of this lab
This lab will exercise your skills in:

* writing classes
* representing data as dictionaries
* using dictionaries to package up arguments
* representing family relations

# A. Quick problems

# A.1 Data class

Define a class `Cat`, with  an `__init__` method that sets instance variables `name, weight, age, temperament` and `colour`.

In [1]:
class Cat:
    def __init__(self, name, weight, age, temperament, colour):
        self.name = name
        self.weight = weight
        self.age = age
        self.temperament = temperament
        self.colour = colour

In [14]:
## Tests
with tick():
    c = Cat("Cooper", 4.0, 4, "terrible", "gray")
    assert hasattr(c, "name") and c.name=="Cooper"
    assert hasattr(c, "weight") and c.weight==4.0
    assert hasattr(c, "age") and c.age==4
    assert hasattr(c, "temperament") and c.temperament=="terrible"
    assert hasattr(c, "colour") and c.colour=="gray"

# A.2 Family names

Create a class `FamilyName` that has an instance variable `first_name` and a **class** variable `last_name` (initialise the `last_name` to "Unknown").

* Make the constructor (`__init__`) take `first_name` as an argument.
* Add an *instance* method `set_last_name` that sets *every* `FamilyName` instance's `last_name`.
* Add an instance method `get_name` which returns the first and last name joined together with a space.

In [2]:
class FamilyName:
    def __init__(self, first_name):
        last_name = "Unknown"
        self.first_name = first_name

    def set_last_name(self, l_name):
        last_name = l_name

    def get_name(self):
        return f"{self.first_name} {last_name}"

In [16]:
## Tests
with tick():
    nm_1 = FamilyName("John")    

    nm_1.set_last_name("Williamson")
    assert nm_1.get_name() == "John Williamson"

    nm_2 = FamilyName("Marco")
    assert nm_2.get_name() == "Marco Williamson"

    nm_1.set_last_name("Polo")
    assert nm_2.get_name() == "Marco Polo"
    assert nm_1.get_name() == "John Polo"

# A.3 Convert a dictionary

The following code defines a list of dictionaries representing different types of dice used in board games, and some functions that operate on those dictionaries. Rewrite this as a class `Die`, where the keys of the dictionaries become instance variables, and the functions defined become methods operating on `self`.

Then, create a list called `dice_class` of instances of `Die` *initialising the values from the dictionary.*

In [17]:
import random

dice = [
    {"name": "d6", "sides": 6, "shape": "cube"},
    {"name": "d4", "sides": 4, "shape": "tetrahedron"},
    {"name": "d12", "sides": 12, "shape": "dodecahedron"},
    {"name": "d8", "sides": 8, "shape": "octahedron"},
    {"name": "d20", "sides": 20, "shape": "icosahedron"},
]

def roll_die(die):
    return random.randint(1, die["sides"])

def opposite_face_sum(die):
    if die["sides"]>4:
        return die["sides"]+1
    else:
        raise ValueError("Die has no opposing sides!")

In [19]:
## Tests
with tick():
    
    assert len(dice_class)==len(dice)
    assert dice_class[0].__class__.__name__=="Die"
    assert dice_class[0].name == dice[0]["name"]
    assert dice_class[0].sides == dice[0]["sides"]
    assert dice_class[0].shape == dice[0]["shape"]
    for d in dice_class:
        print(f"{d.name} rolled a {d.roll_die()}")

    assert dice_class[0].opposite_face_sum()==7    
    assert dice_class[-1].opposite_face_sum()==21

d6 rolled a 3
d4 rolled a 4
d12 rolled a 11
d8 rolled a 6
d20 rolled a 19

# A.4 Type collection

You can get the name of the type of an object using  `type(x).__class__.__name__`. For example:

In [4]:
print((4).__class__.__name__) # int
print(("hey").__class__.__name__) # string
print(({}).__class__.__name__) # dictionary

int
str
dict

Write a class `TypeCollection`. This class will represent a container that can hold objects of different types, but each type has its own separate "space". For example, all `ints` are held separately from all `floats`. 

<div class="alert alert-info">
    
Hint: use an internal dictionary to map the *name* of the type to a list of objects.
</div>

The class should have the following methods:
    
* `add(self, obj)` which adds `obj` to a collection
* `remove(self, obj)` which removes `obj` from a collection (and raises a `ValueError` if the object is not present).
* `remove_all(self, typename)` which removes all objects of type `typename` from the collection
* `get_all(self, typename)` which returns all objects of the type `typename`, as a list.
* `__str__(self)` which returns a string with all of the objects laid out like this (sorted alphabetically in order by name of type):

        float
            1.0
        int
            9
            2
        str
            1
            hey
        tuple
            (3, 4)

In [43]:
## Tests

t = TypeCollection()
t.add(1)
t.add(1.0)
t.add("1")
t.add("hey")
t.add(9)
t.add(2)
t.add((3, 4))
t.remove(1)
t.get_all("float")
with tick():
    assert t.get_all("int")==[9,2]
    assert t.get_all("str")==["1","hey"]
    assert t.get_all("tuple")==[(3,4)]
    t.remove_all("int")
    assert t.get_all("int")==[]

In [44]:
## Tests

# Test here is that a ValueError should be raised
t2 = TypeCollection()
t2.add(5)
t2.add(8)
t2.add("hello")
t2.remove(5.0) # we are trying to remove an element that is not present

ValueError: element not present

--- 

<br>


# B. Family tree

We will work with *family tree*, a data source representing the (fictional) genealogical history of a small town. We'll work with a *very* simplified form of this problem, where we only see a record of births and deaths.

## A person

Let's model a person with a new class, `Person`. We can do noun-verb analysis: we identify **nouns** (in bold) as possible instance variables, and *verbs* (in italics) as possible instance methods.

> * A Person has a **name**. They have a **birth year** and a **death year**. They have a **mother** and a **father**. They have a **unique ID**.
> * We can *ask what someone's age was in a particular year*
> * We can *ask whether someone was alive in a particular year*

## B.1 
Create a class `Person` with appropriate instance variables and methods, given this description. Further, add a `__repr__` method that returns the person's name and birth year as a string. 

**NOTE**: To solve this problem, you will have to first design the structure of the class!

## B.2 Reading data

We have some data about a life events in a town, stored in a file `family_tree.txt`. The format is a chronological log with entries like either:

    year,id,born,name,mother_id,father_id
    
or

    year,id,died 
    
Because names can be repeated, every individual person has a unique ID in this data set. This is just a unique string.
    
For example, a part of the record might be:

    1650,u5019,born,Yatzil McGrue,u2013,u3031
    1651,u2013,died
    
This tells us "Yatzil McGrue" was born in 1650, and had parents with IDs u2013 and u3031. Yatzil's mother died in 1651.

When parent information is not known (e.g. from an immigrant into the town), it is recorded as "---". 

Read this data in using a function `read_family(fname)` that takes a filename and returns a dictionary mapping IDs (like `u2041`) to `Person` objects (using the class you defined above).

In [22]:
## Test
tree = read_family("family_tree.txt")

## B.3 Simple queries

(a) Write a *pure* function `census(tree, year)` that takes a dictionary like the one returned above, and a year, and returns a list of the people alive in that year. 

For example:
    
    census(tree, 1940)
    
    >>> [Meriel Seaver-Corey born 1851,
         Marlon Seaver-Corey born 1855,
         Crew Ewartborn born 1856,
         Brannon Noel-Ewart born 1856,
         .
         .
         .
         Darian Ewart-Foster born 1940,
         Flanagan Falconer born 1940,
         Eliot Mills born 1940,
         Malone Mills born 1940]

In [24]:
census(tree, 1940)

[Meriel Seaver-Corey born 1851,
 Marlon Seaver-Corey born 1855,
 Crew Ewart born 1856,
 Brannon Noel-Ewart born 1856,
 Gypsy Noel-Ewart born 1857,
 Lee Seaver-Corey born 1859,
 London Woodrow born 1859,
 Stacie Woodrow born 1865,
 Sondra Ackerman born 1869,
 Darren Seaver-Corey born 1871,
 Leanna Seaver-Corey born 1872,
 Margo Woodrow born 1873,
 Crew Ackerman born 1874,
 Clint Corey born 1874,
 Elisa Seaver-Corey born 1874,
 Ian Ewart born 1874,
 Brannon Noel-Ewart born 1874,
 Merlyn Ackerman born 1875,
 Caelan Woodrow born 1875,
 Shannon Seaver-Corey born 1875,
 Joselyn Britton born 1875,
 Candyce Ackerman born 1876,
 Tamika Britton born 1876,
 Shayne Noel-Ewart born 1877,
 Hepsie Noel-Ewart born 1878,
 London Woodrow born 1879,
 Gypsy Noel-Ewart born 1879,
 Bethel Yates born 1879,
 Gwenda Ackerman born 1880,
 Shannon Mills born 1881,
 Gordon Noel-Ewart born 1883,
 Candyce Noel-Ewart born 1884,
 Chasity Foster born 1884,
 Cullen Kimberly born 1884,
 Sienna Britton born 1884,
 Cletus Mills born 1884,
 Louis Mills born 1885,
 Meriel Ackerman-Fay born 1885,
 Eldon Ackerman born 1885,
 Tawnee Noel-Ewart born 1886,
 Leanna Ackerman-Fay born 1886,
 Merlyn Ackerman born 1886,
 Forest Ackerman born 1887,
 Trey Falconer born 1888,
 Carrol Ackerman born 1888,
 Tranter Noel-Ackerman born 1890,
 Carran Braddock born 1890,
 Kolton Seaver-Corey born 1891,
 Chloë Ackerman born 1891,
 Elisa Carlyle born 1891,
 Chasity Noel-Ewart born 1892,
 Danita Seaver-Corey born 1892,
 Danita Noel-Ackerman born 1893,
 Merit Yates born 1894,
 Clifton Britton born 1894,
 Roscoe Corey born 1895,
 Kathlyn Yates born 1896,
 Carmen Britton born 1896,
 Clifton Seaver-Corey born 1896,
 Florrie Britton born 1896,
 Marlon Langley-Langley born 1897,
 Sienna Ackerman born 1899,
 Ariel Britton born 1899,
 Alexandrina Woodrow born 1901,
 Florrie Seaver-Corey born 1902,
 Margo Noel-Ewart born 1902,
 Merlyn Ewart born 1903,
 Eliana Ellis born 1904,
 Cali Ackerman born 1905,
 Trey Falconer born 1905,
 Carran Woodrow born 1906,
 Crew Rigby born 1906,
 Keira Ackerman born 1906,
 Joselyn Seaver-Corey born 1906,
 Judd Ewart born 1906,
 Steven Ackerman born 1907,
 Eldon Ackerman born 1907,
 Crew Woodrow born 1908,
 Darren Seaver-Corey born 1908,
 Drake Corey born 1909,
 Cullen Ackerman born 1909,
 Kassandra Woodrow-Corey born 1910,
 Tahnee Foster born 1910,
 Shannon Seaver-Corey born 1910,
 Ellington Ewart born 1911,
 Marvin Woodrow-Corey born 1911,
 Shannon Woodrow born 1912,
 Eliana Seaver-Corey born 1913,
 Cali Seaver-Corey born 1913,
 Cullen Ewart born 1913,
 Kayden Ewart born 1914,
 Kathlyn Ackerman born 1915,
 Lynsay Kimberly born 1916,
 Candyce Yates born 1916,
 Lynsay Ewart born 1916,
 Tisha Langley-Langley born 1916,
 Gordon Yates born 1917,
 Meriel Ackerman born 1918,
 Beckham Mills born 1921,
 Shannon Yates born 1922,
 Caelan Langley-Langley born 1922,
 Carran Falconer born 1922,
 Sienna Ackerman born 1924,
 Brannon Ackerman born 1925,
 Carrol Falconer born 1926,
 Bud Mills born 1927,
 Tisha Langley-Langley born 1928,
 Clint Corey born 1928,
 Merit Ackerman born 1928,
 Genie Pound born 1928,
 Darian Teel born 1929,
 Shayne Seaver-Corey born 1929,
 Carrol Corey born 1929,
 Sienna Ackerman born 1930,
 Candyce Ewart born 1931,
 Dillan Ewart born 1932,
 Trey Noel-Ewart born 1932,
 Joselyn Noel-Ewart born 1932,
 Shayne Ackerman born 1932,
 Eldon Noel-Ewart born 1933,
 Eliana Langley-Langley born 1933,
 Carmen Ackerman born 1933,
 Meriel Ewart born 1933,
 Harold Seaver-Corey born 1933,
 Tisha Falconer born 1934,
 Kassandra Ewart born 1934,
 Jenny Seaver-Corey born 1934,
 Drake Ewart born 1934,
 Kassandra Ewart born 1934,
 Brannon Seaver-Corey born 1935,
 Chasity Mills born 1935,
 Debby Woodrow-Corey born 1935,
 Lee Noel-Ewart born 1935,
 Shannon Howland born 1935,
 Elisa Ewart born 1935,
 Desirae Langley-Langley born 1935,
 Carran Ewart-Foster born 1936,
 Maurine Turner born 1936,
 Allyn Falconer born 1936,
 Shayne Woodrow-Corey born 1936,
 Dannie Noel-Ewart born 1937,
 Lorrie Noel-Ewart born 1937,
 Jamison Ewart born 1937,
 Gwenda Ewart born 1937,
 Brannon Corey born 1937,
 Gwenda Mills born 1937,
 Braiden Ewart born 1937,
 Ellington Ackerman-Ackerman born 1937,
 Cali Falconer born 1938,
 Eldon Baines born 1938,
 Elisa Noel-Ewart born 1938,
 Merlyn Adams born 1938,
 Tisha Ewart born 1938,
 Eliana Woodrow-Corey born 1938,
 Crew Ewart born 1938,
 Ibbie Ackerman born 1938,
 Cali Noel-Ewart born 1939,
 Kassandra Woodrow-Corey born 1939,
 Margo Ewart born 1939,
 Genie Ackerman born 1939,
 Trey Mills born 1939,
 Sienna Ackerman born 1939,
 Allyn Falconer born 1939,
 Allyn Ewart born 1940,
 Beckham Woodrow-Corey born 1940,
 Trey Ackerman born 1940,
 Gwenda Noel-Ewart born 1940,
 Darian Ewart-Foster born 1940,
 Flanagan Falconer born 1940,
 Eliot Mills born 1940,
 Malone Mills born 1940]


(b) Write a function `roll(people, year)` that takes a list of people, and returns a string like the following, listing the name and age of each person in the list, in order, sorted by last name:

    Yatzil McGrue, age 34
    Imhotep Jones, age 69
    Ad-Habip Smith, age 19

Verify you can call it on the result returned from `census` and get a correct looking string returned, similar to below.
    
    roll(census(tree, 1940), 1940)

    >>> Sondra Ackerman, age 71
        Crew Ackerman, age 66
        Merlyn Ackerman, age 65
        Candyce Ackerman, age 64
        Gwenda Ackerman, age 60
        .
        .
        .
        Kathlyn Yates, age 44
        Candyce Yates, age 24
        Gordon Yates, age 23
        Shannon Yates, age 18

In [26]:
print(roll(census(tree, 1940), 1940))

Sondra Ackerman, age 71
Crew Ackerman, age 66
Merlyn Ackerman, age 65
Candyce Ackerman, age 64
Gwenda Ackerman, age 60
Eldon Ackerman, age 55
Merlyn Ackerman, age 54
Forest Ackerman, age 53
Carrol Ackerman, age 52
Chloë Ackerman, age 49
Sienna Ackerman, age 41
Cali Ackerman, age 35
Keira Ackerman, age 34
Steven Ackerman, age 33
Eldon Ackerman, age 33
Cullen Ackerman, age 31
Kathlyn Ackerman, age 25
Meriel Ackerman, age 22
Sienna Ackerman, age 16
Brannon Ackerman, age 15
Merit Ackerman, age 12
Sienna Ackerman, age 10
Shayne Ackerman, age 8
Carmen Ackerman, age 7
Ibbie Ackerman, age 2
Genie Ackerman, age 1
Sienna Ackerman, age 1
Trey Ackerman, age 0
Ellington Ackerman-Ackerman, age 3
Meriel Ackerman-Fay, age 55
Leanna Ackerman-Fay, age 54
Merlyn Adams, age 2
Eldon Baines, age 2
Carran Braddock, age 50
Joselyn Britton, age 65
Tamika Britton, age 64
Sienna Britton, age 56
Clifton Britton, age 46
Carmen Britton, age 44
Florrie Britton, age 44
Ariel Britton, age 41
Elisa Carlyle, age 49
Clint Corey, age 66
Roscoe Corey, age 45
Drake Corey, age 31
Clint Corey, age 12
Carrol Corey, age 11
Brannon Corey, age 3
Eliana Ellis, age 36
Crew Ewart, age 84
Ian Ewart, age 66
Merlyn Ewart, age 37
Judd Ewart, age 34
Ellington Ewart, age 29
Cullen Ewart, age 27
Kayden Ewart, age 26
Lynsay Ewart, age 24
Candyce Ewart, age 9
Dillan Ewart, age 8
Meriel Ewart, age 7
Kassandra Ewart, age 6
Drake Ewart, age 6
Kassandra Ewart, age 6
Elisa Ewart, age 5
Jamison Ewart, age 3
Gwenda Ewart, age 3
Braiden Ewart, age 3
Tisha Ewart, age 2
Crew Ewart, age 2
Margo Ewart, age 1
Allyn Ewart, age 0
Carran Ewart-Foster, age 4
Darian Ewart-Foster, age 0
Trey Falconer, age 52
Trey Falconer, age 35
Carran Falconer, age 18
Carrol Falconer, age 14
Tisha Falconer, age 6
Allyn Falconer, age 4
Cali Falconer, age 2
Allyn Falconer, age 1
Flanagan Falconer, age 0
Chasity Foster, age 56
Tahnee Foster, age 30
Shannon Howland, age 5
Cullen Kimberly, age 56
Lynsay Kimberly, age 24
Marlon Langley-Langley, age 43
Tisha Langley-Langley, age 24
Caelan Langley-Langley, age 18
Tisha Langley-Langley, age 12
Eliana Langley-Langley, age 7
Desirae Langley-Langley, age 5
Shannon Mills, age 59
Cletus Mills, age 56
Louis Mills, age 55
Beckham Mills, age 19
Bud Mills, age 13
Chasity Mills, age 5
Gwenda Mills, age 3
Trey Mills, age 1
Eliot Mills, age 0
Malone Mills, age 0
Tranter Noel-Ackerman, age 50
Danita Noel-Ackerman, age 47
Brannon Noel-Ewart, age 84
Gypsy Noel-Ewart, age 83
Brannon Noel-Ewart, age 66
Shayne Noel-Ewart, age 63
Hepsie Noel-Ewart, age 62
Gypsy Noel-Ewart, age 61
Gordon Noel-Ewart, age 57
Candyce Noel-Ewart, age 56
Tawnee Noel-Ewart, age 54
Chasity Noel-Ewart, age 48
Margo Noel-Ewart, age 38
Trey Noel-Ewart, age 8
Joselyn Noel-Ewart, age 8
Eldon Noel-Ewart, age 7
Lee Noel-Ewart, age 5
Dannie Noel-Ewart, age 3
Lorrie Noel-Ewart, age 3
Elisa Noel-Ewart, age 2
Cali Noel-Ewart, age 1
Gwenda Noel-Ewart, age 0
Genie Pound, age 12
Crew Rigby, age 34
Meriel Seaver-Corey, age 89
Marlon Seaver-Corey, age 85
Lee Seaver-Corey, age 81
Darren Seaver-Corey, age 69
Leanna Seaver-Corey, age 68
Elisa Seaver-Corey, age 66
Shannon Seaver-Corey, age 65
Kolton Seaver-Corey, age 49
Danita Seaver-Corey, age 48
Clifton Seaver-Corey, age 44
Florrie Seaver-Corey, age 38
Joselyn Seaver-Corey, age 34
Darren Seaver-Corey, age 32
Shannon Seaver-Corey, age 30
Eliana Seaver-Corey, age 27
Cali Seaver-Corey, age 27
Shayne Seaver-Corey, age 11
Harold Seaver-Corey, age 7
Jenny Seaver-Corey, age 6
Brannon Seaver-Corey, age 5
Darian Teel, age 11
Maurine Turner, age 4
London Woodrow, age 81
Stacie Woodrow, age 75
Margo Woodrow, age 67
Caelan Woodrow, age 65
London Woodrow, age 61
Alexandrina Woodrow, age 39
Carran Woodrow, age 34
Crew Woodrow, age 32
Shannon Woodrow, age 28
Kassandra Woodrow-Corey, age 30
Marvin Woodrow-Corey, age 29
Debby Woodrow-Corey, age 5
Shayne Woodrow-Corey, age 4
Eliana Woodrow-Corey, age 2
Kassandra Woodrow-Corey, age 1
Beckham Woodrow-Corey, age 0
Bethel Yates, age 61
Merit Yates, age 46
Kathlyn Yates, age 44
Candyce Yates, age 24
Gordon Yates, age 23
Shannon Yates, age 18

(c) Write a function `find_by_name(people, name, year=None)` that will find all the people with the given name. If `year` is specified, only return those people who were alive in that year. Return the list of people in order of birth, earliest first.

**Sample output**:

```Python
find_by_name(tree, "Bethel Wright")
>>> [Bethel Wright born 1650, Bethel Wright born 1850]
```

```Python
find_by_name(tree, "Sonia Bond", 1700)
>>> [Sonia Bond born 1650, Sonia Bond born 1688]
```

```Python
find_by_name(tree, "Debby Boon")
>>> [Debby Boon born 1650, Debby Boon born 1832, Debby Boon born 1833, Debby Boon born 1894]
```

```Python
find_by_name(tree, "Tahnee Gill", 1725)
>>> [Tahnee Gill born 1694, Tahnee Gill born 1724]
```

In [28]:
find_by_name(tree, "Sonia Bond", 1700)

[Sonia Bond born 1650, Sonia Bond born 1688]

(d) Write a function `memorial(tree, year)` that returns a string listing everyone who has died prior to `year`, in ascending order of death date (i.e., oldest death date first), in a format like:

    Yatzil McGrue died 1678, age 74
    Tzecan Barston died 1679, age 56
    
giving the ages at the time of death.

**Sample output**:

```Python3
memorial(tree, 1700)
>>>
    Travis Hyde died 1650, age 0
    Tahnee Gill died 1650, age 0
    Jenny Kimberly died 1651, age 1
    Alexandrina Mills died 1651, age 1
    Harold Kimberly died 1651, age 1
    Orville Kimberly died 1651, age 1
    .
    .
    .
    Lynsay Victors died 1699, age 49
    Lynsay Mills died 1699, age 15
    Hepsie Kimberly died 1699, age 3
    Tahnee Garrard died 1699, age 2
    Darryl Fay died 1699, age 1
```

In [30]:
print(memorial(tree, 1700))

Travis Hyde died 1650, age 0
Tahnee Gill died 1650, age 0
Jenny Kimberly died 1651, age 1
Alexandrina Mills died 1651, age 1
Harold Kimberly died 1651, age 1
Orville Kimberly died 1651, age 1
Eldon Mills died 1651, age 1
Marlon Kimberly died 1651, age 1
Darryl Mills died 1651, age 1
Flanagan Noel died 1652, age 2
Odell Kimberly died 1652, age 2
Odell Kimberly died 1652, age 2
Kayden Starr died 1652, age 2
Trey Corey died 1652, age 1
Diggory Bishop died 1653, age 3
Leanna Derrickson died 1653, age 3
Alexandrina Harris died 1653, age 3
Bryanne Brinley died 1653, age 3
Lacey Mills died 1653, age 3
Braiden Ewart died 1653, age 3
Lacey Starr died 1653, age 3
Eliana Ewart died 1653, age 3
Carrol Starr died 1653, age 3
Tawnee Devine died 1653, age 2
Carrol Starr died 1653, age 2
Carmen Kimberly died 1653, age 2
Genie Corey died 1653, age 2
Drake Simons died 1653, age 1
Lacey Bryson died 1654, age 4
Trey Falconer died 1654, age 4
Allyn Starr died 1654, age 4
Joe Kimberly died 1654, age 4
Gwenda Kimberly died 1654, age 4
Orville Kimberly died 1654, age 2
Odell Corey died 1654, age 2
Bud Seaver died 1655, age 5
Eliana Starr died 1655, age 5
Ian Mills died 1655, age 5
Brannon Mills-Bond died 1655, age 5
Tamika Simen died 1655, age 2
Lorrie Mills died 1656, age 6
Michael Kimberly died 1656, age 6
Retha Mills died 1656, age 6
Viona Devine died 1656, age 6
Lee Corey died 1656, age 3
Kathlyn Gabrielson died 1656, age 2
Elisa Carlyle died 1657, age 7
Brannon Mills died 1657, age 7
Leanna Starr died 1657, age 7
Orville Garrard died 1657, age 6
Candyce Ewart died 1657, age 6
Lorrie Garrard died 1657, age 5
Gwenda Ewart died 1657, age 5
Tawnee Mills died 1657, age 3
Dannie Corey died 1657, age 3
Chasity Kimberly died 1657, age 3
Kolton Godfrey died 1657, age 2
Ricky Macey died 1657, age 1
Travis Starr died 1658, age 8
Carmen Mills died 1658, age 8
Alexandrina Macey died 1658, age 6
Maurine Macey died 1658, age 5
Sondra Starr died 1658, age 3
Elisa Falconer died 1658, age 2
Sondra Ewart died 1659, age 9
Joselyn Starr died 1659, age 9
Margo Mills died 1659, age 7
Clint Falconer died 1659, age 6
Alexandrina Garrard died 1659, age 4
Bud Corey died 1659, age 4
Florrie Garrard died 1659, age 3
Kolton Corey died 1659, age 3
Marvin Starr died 1659, age 2
Lynsay Noel died 1659, age 1
Joss Cornett died 1660, age 7
Cullen Cornett died 1660, age 6
Marvin Garrard died 1660, age 6
Roscoe Falconer died 1660, age 6
Trey Starr died 1660, age 6
Darryl Starr died 1660, age 4
Meade Corey died 1660, age 3
Orville Ewart died 1661, age 11
Joe Kimberly died 1661, age 8
Joselyn Garrard died 1661, age 8
Retha Cornett died 1661, age 6
Lynsay Garrard died 1661, age 4
Joselyn Corey died 1661, age 3
Travis Falconer died 1661, age 1
Tranter Paternoster died 1662, age 10
Steven Falconer died 1662, age 7
Leanna Corey died 1662, age 3
Shannon Falconer died 1662, age 3
Keira Jameson died 1663, age 6
Clint Cornett died 1663, age 6
Shannon Corey died 1663, age 4
Juniper Starr died 1663, age 4
Steven Lacy died 1663, age 4
Retha Fay died 1663, age 3
Forest Falconer died 1663, age 2
Harold Fay-Newell died 1663, age 2
Clifton Starr died 1664, age 14
Tahnee Cornett died 1664, age 12
Joe Falconer died 1664, age 12
Diggory Falconer died 1664, age 6
Madge Peck died 1664, age 3
Darren Fay died 1664, age 1
Carrol Macey died 1665, age 8
Bryanne Garrard died 1665, age 8
Sonia Macey died 1665, age 6
Florrie Macey died 1665, age 5
Shannon Falconer died 1665, age 3
Juniper Blackbourne died 1665, age 3
Stacie Starr died 1666, age 6
Retha Corey died 1666, age 6
Meriel Corey died 1666, age 5
Beckham Starr died 1666, age 4
Juniper Christopherson died 1666, age 2
Caelan Corey died 1666, age 1
Margo Walker died 1667, age 17
Genie Pound died 1667, age 17
Shannon Corey died 1667, age 9
Tahnee Cornett died 1667, age 5
Brannon Fay died 1667, age 3
Dannie Falconer died 1667, age 2
Brannon Blackbourne died 1667, age 1
Cletus Garrard died 1668, age 14
Brooklyn Blackbourne died 1668, age 7
Joss Fay died 1668, age 2
Carrol Abney died 1668, age 2
Judd Fay died 1668, age 1
Drake Corey died 1668, age 1
Alexandrina Harris died 1669, age 19
Tranter Paternoster died 1669, age 19
Danita Devine died 1669, age 19
Trey Fay died 1669, age 7
Gordon Newell died 1669, age 4
Harold Christopherson died 1669, age 3
Tamika Christopherson died 1669, age 1
Grady Corey died 1670, age 6
Tisha Killam died 1670, age 5
Florrie Crawford died 1670, age 4
Brooklyn Christopherson-Beverley died 1670, age 1
Sullivan Fitzroy died 1671, age 4
Meade Corey died 1671, age 3
Carrol Clinton died 1672, age 22
Silver Macey died 1672, age 17
Clint Blackbourne died 1672, age 5
Joselyn Christopherson died 1672, age 1
Elisa Corey died 1672, age 1
Shayne Cornett died 1673, age 23
Dannie Cornett died 1673, age 10
Bud Seaver died 1673, age 1
Keira Jameson died 1674, age 24
Ricky Kimberly died 1674, age 24
Juniper Falconer died 1674, age 10
Sienna Brinley died 1674, age 6
Lorrie Corey died 1674, age 5
Brannon Devine died 1674, age 5
Brannon Barret died 1674, age 4
Dannie Mills died 1674, age 2
Darian Robbins died 1674, age 2
Brooklyn Seaver died 1674, age 2
Chasity Foster died 1675, age 25
Brannon Fay died 1675, age 4
Leanna Christopherson died 1675, age 2
Tahnee Seaver died 1675, age 2
Marlon Kimberly died 1675, age 2
Tamika Seaver died 1675, age 1
Bethel Devine died 1675, age 1
Flanagan Noel died 1676, age 26
Grady Mills died 1676, age 5
Genie Devine died 1676, age 3
Retha Christopherson died 1676, age 2
Madge Christopherson died 1676, age 1
Retha Corwin died 1677, age 27
Sonia Bond died 1677, age 27
Keira Jameson died 1677, age 27
Genie Pound died 1677, age 27
Dillan Emerson died 1677, age 27
Gerrard Fay died 1677, age 8
Grady Robbins died 1677, age 4
Leanna Derrickson died 1678, age 28
Gregg Blackbourne died 1678, age 28
Candyce Fear died 1678, age 28
Crew Starr died 1678, age 7
Darren Mills died 1678, age 4
Jamison Ogden-Ogden died 1678, age 4
Viona Robbins died 1678, age 3
Carran Robbins died 1678, age 2
Trey Falconer died 1679, age 29
Kassandra Fitzroy died 1679, age 10
Michael Christopherson died 1679, age 9
Allyn Christopherson died 1679, age 2
Danita Kimberly died 1679, age 2
Elisa Mills died 1679, age 2
Chloë Britton died 1680, age 30
Tisha Killam-Killam died 1680, age 30
Darian Teel died 1680, age 30
Bud Kimberly died 1680, age 5
Lorrie Ryland died 1680, age 3
Ellington Christopherson died 1680, age 2
Chloë Cornett died 1680, age 1
Clint Devine died 1680, age 1
Hepsie Mills died 1680, age 1
Braiden Starr died 1681, age 31
Caelan Fay died 1681, age 9
Beckham Seaver died 1681, age 6
Chasity Foster died 1681, age 1
London Cornett-Fay died 1681, age 1
Keira Jameson died 1682, age 32
Lee Seaver died 1682, age 11
Clifton Fay died 1682, age 9
Harold Christopherson died 1682, age 6
Dillan Emerson died 1682, age 2
Alexandrina Harris died 1683, age 33
Chasity Foster died 1683, age 33
Carran Braddock died 1683, age 33
Stacie Devine died 1683, age 12
Ricky Cornett died 1683, age 6
Kolton Cornett-Fay died 1683, age 6
Harold Kimberly died 1683, age 5
Hepsie Kimberly died 1683, age 4
Gwenda Devine died 1683, age 3
Jenny Robbins-Starr died 1683, age 3
Tamika Cornett died 1683, age 1
Sonia Bond died 1684, age 34
Darryl Mills died 1684, age 9
Ella Cornett died 1684, age 6
Trey Christopherson died 1684, age 5
Drake Cornett died 1684, age 3
Carmen Cornett died 1684, age 3
Shayne Cornett died 1685, age 35
Carmen Kimberly died 1685, age 9
Braiden Cornett died 1685, age 6
Chasity Ewart died 1685, age 3
Bud Christopherson died 1685, age 3
Maurine Turner died 1685, age 3
Joselyn Ewart-Garrard died 1685, age 2
Tranter Paternoster died 1685, age 2
Stacie Seward died 1686, age 36
Marlon Langley died 1686, age 15
Ella Mills died 1686, age 10
Merlyn Mills died 1686, age 8
Tisha Falconer died 1686, age 6
Carmen Ewart died 1686, age 5
Leanna Derrickson died 1686, age 5
Meriel Mills died 1686, age 5
Braiden Devine died 1686, age 4
Beckham Christopherson died 1686, age 3
Drake Starr died 1686, age 3
Darren Christopherson died 1686, age 2
Cullen Seaver died 1687, age 3
Bethel Wright-Wright died 1687, age 2
Silver Seaver died 1687, age 1
Allyn Robbins died 1688, age 6
Tranter Christopherson died 1688, age 3
Kolton Falconer died 1688, age 2
Viona Trengove died 1689, age 39
Joss Odell died 1689, age 39
Allyn Ewart died 1689, age 39
Sonia Bond died 1689, age 39
Jenny Patterson died 1689, age 39
Debby Ewart died 1689, age 10
Hepsie Falconer died 1689, age 7
Ian Ewart died 1689, age 5
Candyce Cornett died 1689, age 4
Kayden Devine died 1689, age 3
Sonia Mills died 1689, age 3
Eliana Cornett died 1689, age 2
Lacey Ewart died 1689, age 1
Tamika Newell died 1690, age 40
Clifton Devine died 1690, age 14
Kathlyn Christopherson died 1690, age 10
Orville Kimberly died 1690, age 9
Carmen Cornett died 1690, age 8
Drake Robbins died 1690, age 7
Sienna Falconer-Kimberly died 1690, age 3
Gregg Mills died 1690, age 3
Hepsie Devine died 1690, age 3
Marvin Cornett-Mills died 1690, age 2
Silver Kimberly died 1690, age 1
Cali Fox died 1692, age 42
Meriel Reynolds died 1692, age 42
Tisha Killam died 1692, age 42
Teagan Falconer died 1692, age 9
Travis Hyde died 1692, age 9
Erin Devine died 1693, age 12
Jenny Seaver died 1693, age 6
Cali Devine died 1693, age 5
Maurine Cornett died 1693, age 4
Harold Seaver died 1693, age 3
Bryanne Kimberly died 1693, age 3
Sondra Kimberly died 1693, age 2
Chloë Falconer-Robbins died 1693, age 1
Debby Boon died 1694, age 44
Kayden Garrard died 1694, age 44
Candyce Falconer died 1694, age 9
Dannie Seaver died 1694, age 6
Carran Fay died 1694, age 3
Steven Fay died 1694, age 2
Roscoe Allen died 1695, age 45
Trey Falconer died 1695, age 45
Carmen Beverley died 1695, age 45
Orville Cooke died 1695, age 45
Kathlyn Gabrielson died 1695, age 45
Darian Cornett died 1695, age 11
Genie Ewart died 1695, age 8
Cali Ewart died 1695, age 5
Kassandra Falconer-Robbins died 1695, age 4
Allyn Seaver died 1695, age 3
Flanagan Seaver died 1695, age 2
Flanagan Jekyll died 1695, age 2
Sonia Bond died 1696, age 46
Kassandra Starr died 1696, age 9
Viona Jekyll died 1696, age 4
Forest Greene died 1697, age 47
Joselyn Godfrey died 1697, age 47
Sienna Bunker died 1697, age 47
Kolton Macey died 1697, age 47
Darren Fay died 1697, age 23
Dannie Mills died 1697, age 9
Eliana Seaver died 1697, age 8
Teagan Kimberly died 1697, age 4
Eliana Kimberly died 1697, age 3
Maurine Falconer died 1697, age 2
Retha Fay died 1697, age 1
Carran Mills died 1697, age 1
Braiden Mills died 1698, age 16
Braiden Starr died 1698, age 12
Tahnee Mills-Ewart died 1698, age 9
Kathlyn Jekyll died 1698, age 7
Joselyn Kimberly died 1698, age 6
Cletus Corey died 1698, age 4
Brooklyn Jekyll died 1698, age 3
Erin Jekyll died 1698, age 1
Sondra Fay died 1698, age 1
Teagan Porcher died 1699, age 49
Gerrard Robbins died 1699, age 49
Lynsay Victors died 1699, age 49
Lynsay Mills died 1699, age 15
Hepsie Kimberly died 1699, age 3
Tahnee Garrard died 1699, age 2
Darryl Fay died 1699, age 1

## B.4 Class-ify
A dictionary of `People` is fine to work with, but as things get more complicated it would be useful to collect these operations into a class. 

* Create a class `FamilyTree` that stores a dictionary like we have been using, and add the methods `census(year)` and `find_by_name(name, year)` to it. 
* Create a **class method** `load_from_file` that will return a `FamilyTree` from a file, by calling `read_family`. We will extend this class in the next problems.

## B.5 Family relations
Add three new methods to `FamilyTree`:
    
* `parents(person)` -- returns a pair of the parents of a Person. Note: this should return two Person objects, *not* two IDs!    Return None for parents that aren't known ("---" in the data).
* `siblings(person)` -- returns a list of siblings of a Person (empty list if Person has no siblings)
* `children(person)` -- returns a list of the the children of a Person (empty list if Person has no children)

**Test** that these work correctly (try and think of a smart way of doing this)

In [32]:
f = FamilyTree.load_from_file("family_tree.txt")
f.census(1940)

[Meriel Seaver-Corey born 1851,
 Marlon Seaver-Corey born 1855,
 Crew Ewart born 1856,
 Brannon Noel-Ewart born 1856,
 Gypsy Noel-Ewart born 1857,
 Lee Seaver-Corey born 1859,
 London Woodrow born 1859,
 Stacie Woodrow born 1865,
 Sondra Ackerman born 1869,
 Darren Seaver-Corey born 1871,
 Leanna Seaver-Corey born 1872,
 Margo Woodrow born 1873,
 Crew Ackerman born 1874,
 Clint Corey born 1874,
 Elisa Seaver-Corey born 1874,
 Ian Ewart born 1874,
 Brannon Noel-Ewart born 1874,
 Merlyn Ackerman born 1875,
 Caelan Woodrow born 1875,
 Shannon Seaver-Corey born 1875,
 Joselyn Britton born 1875,
 Candyce Ackerman born 1876,
 Tamika Britton born 1876,
 Shayne Noel-Ewart born 1877,
 Hepsie Noel-Ewart born 1878,
 London Woodrow born 1879,
 Gypsy Noel-Ewart born 1879,
 Bethel Yates born 1879,
 Gwenda Ackerman born 1880,
 Shannon Mills born 1881,
 Gordon Noel-Ewart born 1883,
 Candyce Noel-Ewart born 1884,
 Chasity Foster born 1884,
 Cullen Kimberly born 1884,
 Sienna Britton born 1884,
 Cletus Mills born 1884,
 Louis Mills born 1885,
 Meriel Ackerman-Fay born 1885,
 Eldon Ackerman born 1885,
 Tawnee Noel-Ewart born 1886,
 Leanna Ackerman-Fay born 1886,
 Merlyn Ackerman born 1886,
 Forest Ackerman born 1887,
 Trey Falconer born 1888,
 Carrol Ackerman born 1888,
 Tranter Noel-Ackerman born 1890,
 Carran Braddock born 1890,
 Kolton Seaver-Corey born 1891,
 Chloë Ackerman born 1891,
 Elisa Carlyle born 1891,
 Chasity Noel-Ewart born 1892,
 Danita Seaver-Corey born 1892,
 Danita Noel-Ackerman born 1893,
 Merit Yates born 1894,
 Clifton Britton born 1894,
 Roscoe Corey born 1895,
 Kathlyn Yates born 1896,
 Carmen Britton born 1896,
 Clifton Seaver-Corey born 1896,
 Florrie Britton born 1896,
 Marlon Langley-Langley born 1897,
 Sienna Ackerman born 1899,
 Ariel Britton born 1899,
 Alexandrina Woodrow born 1901,
 Florrie Seaver-Corey born 1902,
 Margo Noel-Ewart born 1902,
 Merlyn Ewart born 1903,
 Eliana Ellis born 1904,
 Cali Ackerman born 1905,
 Trey Falconer born 1905,
 Carran Woodrow born 1906,
 Crew Rigby born 1906,
 Keira Ackerman born 1906,
 Joselyn Seaver-Corey born 1906,
 Judd Ewart born 1906,
 Steven Ackerman born 1907,
 Eldon Ackerman born 1907,
 Crew Woodrow born 1908,
 Darren Seaver-Corey born 1908,
 Drake Corey born 1909,
 Cullen Ackerman born 1909,
 Kassandra Woodrow-Corey born 1910,
 Tahnee Foster born 1910,
 Shannon Seaver-Corey born 1910,
 Ellington Ewart born 1911,
 Marvin Woodrow-Corey born 1911,
 Shannon Woodrow born 1912,
 Eliana Seaver-Corey born 1913,
 Cali Seaver-Corey born 1913,
 Cullen Ewart born 1913,
 Kayden Ewart born 1914,
 Kathlyn Ackerman born 1915,
 Lynsay Kimberly born 1916,
 Candyce Yates born 1916,
 Lynsay Ewart born 1916,
 Tisha Langley-Langley born 1916,
 Gordon Yates born 1917,
 Meriel Ackerman born 1918,
 Beckham Mills born 1921,
 Shannon Yates born 1922,
 Caelan Langley-Langley born 1922,
 Carran Falconer born 1922,
 Sienna Ackerman born 1924,
 Brannon Ackerman born 1925,
 Carrol Falconer born 1926,
 Bud Mills born 1927,
 Tisha Langley-Langley born 1928,
 Clint Corey born 1928,
 Merit Ackerman born 1928,
 Genie Pound born 1928,
 Darian Teel born 1929,
 Shayne Seaver-Corey born 1929,
 Carrol Corey born 1929,
 Sienna Ackerman born 1930,
 Candyce Ewart born 1931,
 Dillan Ewart born 1932,
 Trey Noel-Ewart born 1932,
 Joselyn Noel-Ewart born 1932,
 Shayne Ackerman born 1932,
 Eldon Noel-Ewart born 1933,
 Eliana Langley-Langley born 1933,
 Carmen Ackerman born 1933,
 Meriel Ewart born 1933,
 Harold Seaver-Corey born 1933,
 Tisha Falconer born 1934,
 Kassandra Ewart born 1934,
 Jenny Seaver-Corey born 1934,
 Drake Ewart born 1934,
 Kassandra Ewart born 1934,
 Brannon Seaver-Corey born 1935,
 Chasity Mills born 1935,
 Debby Woodrow-Corey born 1935,
 Lee Noel-Ewart born 1935,
 Shannon Howland born 1935,
 Elisa Ewart born 1935,
 Desirae Langley-Langley born 1935,
 Carran Ewart-Foster born 1936,
 Maurine Turner born 1936,
 Allyn Falconer born 1936,
 Shayne Woodrow-Corey born 1936,
 Dannie Noel-Ewart born 1937,
 Lorrie Noel-Ewart born 1937,
 Jamison Ewart born 1937,
 Gwenda Ewart born 1937,
 Brannon Corey born 1937,
 Gwenda Mills born 1937,
 Braiden Ewart born 1937,
 Ellington Ackerman-Ackerman born 1937,
 Cali Falconer born 1938,
 Eldon Baines born 1938,
 Elisa Noel-Ewart born 1938,
 Merlyn Adams born 1938,
 Tisha Ewart born 1938,
 Eliana Woodrow-Corey born 1938,
 Crew Ewart born 1938,
 Ibbie Ackerman born 1938,
 Cali Noel-Ewart born 1939,
 Kassandra Woodrow-Corey born 1939,
 Margo Ewart born 1939,
 Genie Ackerman born 1939,
 Trey Mills born 1939,
 Sienna Ackerman born 1939,
 Allyn Falconer born 1939,
 Allyn Ewart born 1940,
 Beckham Woodrow-Corey born 1940,
 Trey Ackerman born 1940,
 Gwenda Noel-Ewart born 1940,
 Darian Ewart-Foster born 1940,
 Flanagan Falconer born 1940,
 Eliot Mills born 1940,
 Malone Mills born 1940]

In [33]:
person = f.find_by_name("Joss Ewart")[-1]
print(type(person))
print("-"*20)
print("Parents: ",f.parents(person))
print("-"*20)
print("Children: ",f.children(person))
print("-"*20)
print("Siblings: ",f.siblings(person))

<class '__main__.Person'>
--------------------
Parents:  [Dannie Ackerman born 1819, Meade Ewart born 1794]
--------------------
Children:  [Odell Corey born 1858, Eliot Corey born 1859, Ibbie Corey born 1860, Shannon Corey born 1861, Allyn Corey born 1862, Eliot Corey born 1863, Darryl Corey-Ewart born 1864, Teagan Corey born 1865, Beckham Corey born 1866, Carmen Ackerman born 1868, Sondra Ackerman born 1869, Leanna Ackerman born 1870, Kayden Ackerman born 1871, Malone Ackerman born 1872, Desirae Ackerman born 1873, Bethel Ackerman born 1874]
--------------------
Siblings:  [Cletus Ewart born 1845, Silver Ewart born 1855, Ricky Ewart born 1851, Crew Ewart born 1856, Leanna Ewart born 1846, Retha Ewart born 1847, Caelan Ewart born 1852, Juniper Ewart born 1836, Marlon Ewart born 1837, Joss Ewart born 1838, Caelan Ackerman born 1839, Tranter Paternoster born 1853, Forest Ewart born 1848, Chasity Ewart born 1840, Diggory Ewart born 1857, Michael Ewart born 1841, Chloë Ewart born 1858, Dannie Ewart born 1849, Hepsie Ewart born 1842, Sonia Ewart born 1843, Lynsay Ewart born 1850, Michael Ewart born 1854, Steven Ewart born 1844]

## B.6 Harder queries

Add the following methods. These methods require the use of *recursion* to solve the problem.

An **ancestor** is a parent, grandparent, great-grandparent and so on.
A **descendent** is a child, grandchild, and so on.
A **nearest common ancestor** between two people is the most direct ancestor that two people share. For example, the nearest common ancestor of a niece and uncle is the niece's grandparent. The nearest common ancestor of siblings is their parent.
    
* `is_ancestor(a, b)` returns True if a is an ancestor of b 
* `is_descendent(a, b)` returns True if a is a descendent of b 
* `nearest_common_ancestor(a,b)` returns a Person who is a nearest common ancestor of `a` and `b` (or None, if no such ancestor). There may be more than one nearest common ancestor, in which case just return any one.
* `related(a, b)` returns True if two people have a common ancestor

In [12]:
# run this cell to change the width of the current notebook
# this saves you from scrolling to the side when a code line is too long

from IPython.core.display import display, HTML
display(HTML("<style>.container { width:80% !important; }</style>"))